spring.application.name=camunda-process-demo
server.port=8082
camunda.client.cloud.cluster-id=6907d51b-17d5-4bc9-97cb-6b561d9c103f
camunda.client.cloud.region=dsm-1
camunda.client.auth.client-id=~jtMyU_akqyCI9NyICZAUCxcZci0OR75
camunda.client.auth.client-secret=8hr12k_t5SeAmEMxuO5kQ1sYvCvhE6E6Q9ZbPMC00AQ355AVZ3odqXF7leYoplAI
camunda.client.prefer-rest-over-grpc=false
# REST API for user-task search/complete
camunda.client.rest-address=https://dsm-1.zeebe.camunda.io/6907d51b-17d5-4bc9-97cb-6b561d9c103f
